name: "Terraform CI/CD Pipeline"

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  terraform:
    name: "Terraform Validate & Apply"
    runs-on: ubuntu-latest

    # Permissões necessárias para interagir com o repositório
    permissions:
      contents: read

    steps:
    - name: Checkout do Repositório
      uses: actions/checkout@v4

    # 1. Levanta o LocalStack usando o compose.yml e passa o token
    - name: Iniciar LocalStack
      run: docker compose up -d
      env:
        LOCALSTACK_AUTH_TOKEN: ${{ secrets.LOCALSTACK_AUTH_TOKEN }}

    # 2. Aguarda até que o LocalStack esteja pronto para receber conexões do Terraform
    - name: Aguardar o LocalStack
      run: |
        echo "Aguardando o LocalStack iniciar..."
        while ! curl -s http://localhost:4566/_localstack/health > /dev/null; do
          sleep 3
        done
        echo "LocalStack pronto!"

    - name: Configurar a Ferramenta Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: 1.8.0

    - name: Terraform Init
      run: terraform init
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_DEFAULT_REGION: us-east-1

    - name: Terraform Validate
      run: terraform validate

    - name: Terraform Plan (Pré-visualização de Alterações)
      run: terraform plan -no-color
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_DEFAULT_REGION: us-east-1

    - name: Terraform Apply (Execução Automática na Main)
      if: github.ref == 'refs/heads/main' && github.event_name == 'push'
      run: terraform apply -auto-approve
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_DEFAULT_REGION: us-east-1