name: "Terraform CI/CD Pipeline"

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  terraform:
    name: "Terraform Validate & Apply"
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./aws_infra

    permissions:
      contents: read

    steps:
    - name: Checkout do Repositório
      uses: actions/checkout@v4

    - name: Iniciar LocalStack
      run: docker compose up -d
      env:
        LOCALSTACK_AUTH_TOKEN: ${{ secrets.LOCALSTACK_AUTH_TOKEN }}

    - name: Aguardar o LocalStack
      run: |
        echo "Aguardando o LocalStack iniciar..."
        counter=0
        while ! curl -s http://localhost:4566/_localstack/health > /dev/null; do
          sleep 3
          counter=$((counter+1))
          if [ $counter -gt 20 ]; then
            echo "ERRO: O LocalStack demorou muito a responder. A mostrar logs:"
            docker compose logs
            exit 1
          fi
        done
        echo "LocalStack pronto!"

    - name: Criar S3 Bucket no LocalStack
      run: |
        echo "A criar o bucket S3 para o backend do Terraform..."
        aws --endpoint-url=http://localhost:4566 s3 mb s3://renato-terraform-state
      env:
        AWS_ACCESS_KEY_ID: test
        AWS_SECRET_ACCESS_KEY: test
        AWS_DEFAULT_REGION: us-east-1
    
    - name: Criar DynamoDB Table no LocalStack
      run: |
        echo "A criar a tabela DynamoDB para o backend do Terraform..."
        aws --endpoint-url=http://localhost:4566 dynamodb create-table \
          --table-name renato-terraform-lock \
          --attribute-definitions AttributeName=LockID,AttributeType=S \
          --key-schema AttributeName=LockID,KeyType=HASH \
          --provisioned-throughput ReadCapacityUnits=5,WriteCapacityUnits=5
      env:
        AWS_ACCESS_KEY_ID: test
        AWS_SECRET_ACCESS_KEY: test
        AWS_DEFAULT_REGION: us-east-1

    - name: Configurar a Ferramenta Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: 1.8.0

    - name: Terraform Init
      run: terraform init
      env:
        TF_LOG: DEBUG
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_DEFAULT_REGION: us-east-1

    - name: Terraform Validate
      run: terraform validate

    - name: Terraform Plan (Pré-visualização de Alterações)
      run: terraform plan -no-color
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_DEFAULT_REGION: us-east-1

    - name: Terraform Apply (Execução Automática na Main)
      if: github.ref == 'refs/heads/main' && github.event_name == 'push'
      run: terraform apply -auto-approve
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_DEFAULT_REGION: us-east-1